### ISSUE TITLE
'RuntimeError: CUDA out of memory' on P100

### ISSUE THREAD

**Issue by HalleyStarbun** [justin-bennington/somewhere-ml#11]
Hi there,

I'm using Colab Pro to do some ML experiments and often fail to initialise the RN50x4 CLIP model. Sometimes I even have trouble getting the RN101 model to load up. RN50x16 has never worked in my experience. The notebook is running on a P100 GPU and mentions that "x4 and x16 models for CLIP may not work reliably on lower-memory machines".

I'm just wondering if I need an even more capable GPU (in terms of VRAM) or if there is some problem with the code? I'm not an expert with Tensorflow/ML so apologies if there's a simple solution to this.

**Comment by HalleySystems** [comment]
Ah, sorry. The wording made it sound like it was possible on Colab. Thank you.
