### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'content/drive/MyDrive/FolderName/ProjectName/vqgan-steps/0235.png'

### ISSUE THREAD

**Issue by Wanh3daSkairipa** [justin-bennington/somewhere-ml#3]
when i try to use ISR Execution that error pops up...   also if i try to use Generate a video after that error i get this error FileNotFoundError: [Errno 2] No such file or directory: '/content/vqgan-steps/0009.png'......... am i doing something wrong?

**Comment by Wanh3daSkairipa** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/90260380/132390367-07aa6fbb-9022-4933-a1a3-09e6f33c02f0.png)

**Comment by justin-bennington** [comment]
ISR removed and replaced with ESRGAN and absolute directory assignment
